### ISSUE TITLE
Zenodo Backup

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/carl-storm#3]
While Storm is backed up to Zenodo, Carl is not.

**Comment by volkm** [comment]
Integration with Zenodo is activated now, but will only be available for new releases.
I will try the script from https://github.com/zenodo/zenodo/issues/1463#issuecomment-1468932469 to get the old releases as well.

**Comment by volkm** [comment]
There are no old releases of carl master14 and therefore not yet anything on Zenodo. The next release will make it available though.

**Comment by sjunges** [comment]
This seems to be working! Thanks @volkm
