### ISSUE TITLE
Compiler warnings

### ISSUE THREAD

**Issue by sjunges** [moves-rwth/carl-storm#33]
On apple m1, i get the following warnings:

clang: warning: argument unused during compilation: '-msse' [-Wunused-command-line-argument]
clang: warning: argument unused during compilation: '-msse2' [-Wunused-command-line-argument]

**Comment by volkm** [comment]
My proposal would be to use `-march=native` instead. This enables -msse and -msse2 by default on x86-64  ([source](https://stackoverflow.com/questions/10686638/whats-the-difference-among-cflgs-sse-options-of-msse-msse2-mssse3-msse4)). Similar to Storm I would introduce a `CARL_PORTABLE` flag and disable native on Apple Silicon.

**Comment by tquatmann** [comment]
FYI: `-mach=native`  appears to work with recent AppleClang (in my case `clang-1500.3.9.4` with an M1Pro machine)

**Comment by volkm** [comment]
Resolved via #35.
